language: ruby
before_install: rvm install 2.2.4 && rvm user 2.2.4
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
after_install: bundle exec rake db:setup